import React from 'react'
import './globals.css'
import { RenderThemeStylesheet, ThemeProvider } from '@/styled-css-modules/theme'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <ThemeProvider>
        <head>
          <RenderThemeStylesheet />
        </head>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  )
}
